# Generated by Django 6.0.1 on 2026-06-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('one_to_one', 'One-to-one'), ('group', 'Group')], max_length=20),
        ),
    ]
