# Generated by Django 6.0.1 on 2026-07-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_course_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
