# Generated by Django 6.0.1 on 2026-07-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_place_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('physical', 'Physical'), ('online', 'Online')], default='physical', max_length=20),
        ),
    ]
