# Generated by Django 6.0.1 on 2026-07-29 08:54

import django.db.models.deletion
from django.db import migrations, models


def copy_course_place_to_meeting_default(apps, schema_editor):
    CourseMeeting = apps.get_model("courses", "CourseMeeting")
    database_alias = schema_editor.connection.alias

    meetings = (
        CourseMeeting.objects
        .using(database_alias)
        .select_related("course")
        .filter(default_place__isnull=True)
    )

    batch = []
    for meeting in meetings.iterator(chunk_size=1000):
        meeting.default_place_id = meeting.course.place_id
        batch.append(meeting)

        if len(batch) == 1000:
            CourseMeeting.objects.using(database_alias).bulk_update(
                batch,
                ["default_place"],
            )
            batch.clear()

    if batch:
        CourseMeeting.objects.using(database_alias).bulk_update(
            batch,
            ["default_place"],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_location_city_alter_location_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemeeting',
            name='default_place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_for_course_meetings', to='courses.place'),
        ),
        migrations.RunPython(
            copy_course_place_to_meeting_default,
            migrations.RunPython.noop,
        ),
    ]
