# Generated by Django 6.0.1 on 2026-07-29 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_remove_coursemeeting_place_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='place',
            new_name='default_place',
        ),
    ]
