# Generated by Django 6.0.1 on 2026-06-04 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('StreetAddress', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=7)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_type', models.CharField(choices=[('on-to-one', 'One-to-one'), ('group', 'Group')], max_length=20)),
                ('subject', models.CharField(choices=[('guitar', 'Guitar'), ('ukulele', 'Ukulele')], max_length=20)),
                ('term_type', models.CharField(choices=[('school_term', 'School term'), ('all_year', 'All year')], max_length=20)),
                ('duration_type', models.CharField(choices=[('one_off', 'One-off'), ('date_range', 'Date range')], max_length=20)),
                ('max_participants', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('days_of_week', models.CharField(blank=True, help_text='MO,TU,WE,TH,FR,SA,SU', max_length=20)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses_taught', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='courses_attended', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.location')),
            ],
        ),
        migrations.CreateModel(
            name='ClassMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('cancelled', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_meetings_taught', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='class_meetings_attended', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='classes.course')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='classes.location')),
            ],
        ),
    ]
