# Generated by Django 6.0.1 on 2026-06-05 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='StreetAddress',
            new_name='street_address',
        ),
        migrations.AddField(
            model_name='classmeeting',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='name',
            field=models.CharField(default='Unnamed course', max_length=200),
            preserve_default=False,
        ),
    ]
